name: colocalisation-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - jonaszierer
dependencies:
  - conda-forge::r-dplyr=0.8.0.1
  - conda-forge::r-optparse=1.6.1
  - conda-forge::r-devtools=2.0.1
  - conda-forge::r-readr=1.3.1
  - conda-forge::r-purrr=0.3.2
  - conda-forge::r-tidyr=0.8.3
  - conda-forge::r-purrrlyr=0.0.4
  - conda-forge::r-assertthat=0.2.1
  - bioconda::r-coloc=3.1
  - bioconda::tabix=0.2.6
  - bioconda::csvtk=0.18.2
  - bioconda::bioconductor-rsamtools=1.34.0
  - bioconda::bioconductor-qvalue=2.14.0
  - jonaszierer::r-gwasvcf=0.1.5
